### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ben-harvey**
Add details about why this repo exists

### CODE REVIEW

**Review by hundt-corbalt — COMMENTED** [review]
Add a note indicating where the releases are created from?

**Comment by ben-harvey** [comment]
> Add a note indicating where the releases are created from?

@hundt-corbalt I say "This (public) repo is used to store releases of the `report-event` CLI from the [mac-fc-dso-metrics repo](https://github.com/Enterprise-CMCS/mac-fc-dso-metrics)." Do you mean something other than that?

**Comment by hundt-corbalt** [comment]
> > Add a note indicating where the releases are created from?
> 
> @hundt-corbalt I say "This (public) repo is used to store releases of the `report-event` CLI from the [mac-fc-dso-metrics repo](https://github.com/Enterprise-CMCS/mac-fc-dso-metrics)." Do you mean something other than that?

Well that says what is in this repo but not how it gets there :) I guess maybe you think it's obvious? In that case I'm fine with leaving it as is

**Comment by ben-harvey** [comment]
> > > Add a note indicating where the releases are created from?
> > 
> > 
> > @hundt-corbalt I say "This (public) repo is used to store releases of the `report-event` CLI from the [mac-fc-dso-metrics repo](https://github.com/Enterprise-CMCS/mac-fc-dso-metrics)." Do you mean something other than that?
> 
> Well that says what is in this repo but not how it gets there :) I guess maybe you think it's obvious? In that case I'm fine with leaving it as is

Ah, I see. Yeah, this README is really just so future developers can connect the dots between the repos, I figure anyone who really cares will just go look at the DSO metrics repo and figure it out

**Pull request merged**
